name: my-awesome-app

on:
  push:
    branches:
      - production

env:
  # NEXUS_DOCKER_REGISTRY: sdevang/my-awesome-app
  DOCKERHUB_IMAGE_NAME: sdevang/my-awesome-app

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: generate-env-vars
      run: |
        TAG=$(cat VERSION)
        echo "export TAG=$TAG" > .variables
        echo "export DOCKERHUB_IMAGE_WITH_TAG=$DOCKERHUB_IMAGE_NAME:$TAG" >> .variables

    - name: deploy-to-production
      run: |
        source .variables
        git clone https://sdevang:${{ secrets.PAT }}@github.com/sdevang/my-awesome-app-cd.git
        git config --global user.email "dev@gocloudify.com"
        git config --global user.name "GitHub Runner"
        git checkout -B production
        cd my-awesome-app-cd/deployments/overlay/production
        kustomize edit set image $DOCKERHUB_IMAGE_NAME=$DOCKERHUB_IMAGE_WITH_TAG
        git commit -am 'Production image update'
        git push origin production